export const ALLOWED_PREFERENCES = [
    "Technology",
    "Health",
    "Science",
    "Travel",
    "Food",
    "Education",
    "Finance",
    "Sports",
    "Entertainment",
    "Politics",
    "Environment",
    "Art",
    "History",
    "Culture",
    "Business",
    "Self-Improvement",
    "Psychology",
    "Spirituality",
    "Fitness",
    "Parenting",
    "Gaming",
    "Photography",
    "Startups",
    "Programming",
    "Space",
    "Animals",
    "Nature",
    "Productivity",
    "Career Development",
    "Movies",
    "Music",
    "Books",
    "Fashion",
    "Mental Health",
    "Relationships",
    "Lifestyle",
    "Personal Finance",
    "Marketing",
    "Design",
    "Philosophy",
    "Education Technology",
    "Artificial Intelligence",
    "Machine Learning",
    "Cryptocurrency",
    "Investing",
    "Leadership",
    "Economy",
    "News",
    "Languages",
] as const;

import { z } from "zod";

export const preferencesSchema = z.object({
    preferences: z.array(z.enum(ALLOWED_PREFERENCES)).nonempty("At least one preference must be selected."),
});
